# Generated by Django 5.2.17 on 2026-09-25 20:03

import django.db.models.deletion
from django.db import migrations, models

def initialize_existing_gold(apps, schema_editor):
    GoldPurchase = apps.get_model('finance', 'GoldPurchase')
    GoldPurchase.objects.all().update(remaining_weight_grams=models.F('weight_grams'), name='Gold')


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goldprice',
            name='source_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goldpurchase',
            name='name',
            field=models.CharField(default='طلا', max_length=120),
        ),
        migrations.AddField(
            model_name='goldpurchase',
            name='remaining_weight_grams',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.RunPython(initialize_existing_gold, migrations.RunPython.noop),
        migrations.CreateModel(
            name='GoldSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField()),
                ('weight_grams', models.DecimalField(decimal_places=3, max_digits=12)),
                ('amount_received', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gold_sale_deposits', to='finance.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gold_sales', to='finance.household')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='finance.goldpurchase')),
            ],
        ),
    ]
