# Generated by Django 5.2.17 on 2026-09-25 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_goldprice_source_updated_at_goldpurchase_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goldpurchase',
            name='name',
            field=models.CharField(default='Gold', max_length=120),
        ),
    ]
