# Generated by Django 5.2.17 on 2026-09-25 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_goldpurchase_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه'), ('transfer', 'انتقال'), ('debt_receipt', 'دریافت اصل طلب'), ('debt_payment', 'پرداخت اصل بدهی')], max_length=16),
        ),
        migrations.CreateModel(
            name='Obligation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('expected_payment', 'دریافت مورد انتظار'), ('bill', 'قبض'), ('debt_owed', 'بدهی خانواده'), ('debt_receivable', 'طلب خانواده')], max_length=20)),
                ('counterparty', models.CharField(max_length=120)),
                ('amount', models.BigIntegerField()),
                ('settled_amount', models.BigIntegerField(default=0)),
                ('due_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('partial', 'بخشی تسویه شده'), ('settled', 'تسویه شده')], default='pending', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligations', to='finance.category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('destination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expected_payments', to='finance.account')),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligations', to='finance.household')),
            ],
        ),
        migrations.CreateModel(
            name='ObligationSettlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('obligation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='finance.obligation')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='obligation_settlement', to='finance.transaction')),
            ],
        ),
        migrations.AddConstraint(
            model_name='obligation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='obligation_positive_amount'),
        ),
        migrations.AddConstraint(
            model_name='obligation',
            constraint=models.CheckConstraint(condition=models.Q(('settled_amount__gte', 0), ('settled_amount__lte', models.F('amount'))), name='obligation_valid_settled_amount'),
        ),
    ]
