# Generated by Django 5.2.17 on 2026-09-25 21:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_transaction_type_obligation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('income', 'درآمد'), ('expense', 'هزینه'), ('transfer', 'انتقال'), ('debt_receipt', 'دریافت اصل طلب'), ('debt_payment', 'پرداخت اصل بدهی'), ('loan_borrowed', 'دریافت اصل وام'), ('loan_lent', 'پرداخت اصل وام')], max_length=16),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('borrowed', 'وام گرفته\u200cشده'), ('lent', 'وام داده\u200cشده')], max_length=8)),
                ('party', models.CharField(max_length=120)),
                ('original_principal', models.BigIntegerField()),
                ('start_date', models.DateField()),
                ('maturity_date', models.DateField(blank=True, null=True)),
                ('annual_interest_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total_interest', models.BigIntegerField(default=0)),
                ('repaid_principal', models.BigIntegerField(default=0)),
                ('repaid_interest', models.BigIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='finance.household')),
                ('origination_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originated_loans', to='finance.account')),
                ('origination_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='originated_loan', to='finance.transaction')),
            ],
        ),
        migrations.CreateModel(
            name='LoanInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='installments', to='finance.loan')),
            ],
            options={
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('principal_amount', models.BigIntegerField(default=0)),
                ('interest_amount', models.BigIntegerField(default=0)),
                ('idempotency_key', models.UUIDField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('interest_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_interest_repayment', to='finance.transaction')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repayments', to='finance.loan')),
                ('principal_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loan_principal_repayment', to='finance.transaction')),
            ],
            options={
                'ordering': ['date', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('original_principal__gt', 0)), name='loan_positive_principal'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('repaid_principal__gte', 0), ('repaid_principal__lte', models.F('original_principal'))), name='loan_valid_repaid_principal'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.CheckConstraint(condition=models.Q(('total_interest__gte', 0), ('repaid_interest__gte', 0), ('repaid_interest__lte', models.F('total_interest'))), name='loan_valid_interest'),
        ),
        migrations.AddConstraint(
            model_name='loaninstallment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='loan_installment_positive'),
        ),
        migrations.AddConstraint(
            model_name='loanrepayment',
            constraint=models.CheckConstraint(condition=models.Q(('principal_amount__gte', 0), ('interest_amount__gte', 0), models.Q(('principal_amount__gt', 0), ('interest_amount__gt', 0), _connector='OR')), name='loan_repayment_positive'),
        ),
    ]
